name: Changelog check
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Changelog check
        uses: dangoslen/changelog-enforcer@v3
        with:
          changeLogPath: 'CHANGES.md'
          skipLabels: 'Skip-Changelog'
